project:
  type: website
  output-dir: docs
website:
  title: "Aayush Agrawal"
  site-url: https://aayushmnit.com/
  description: "Aayush's personal website"
  repo-url: https://github.com/aayushmnit/aayushmnit.github.io
  repo-actions: [edit, issue]
  open-graph: true
  google-analytics: "G-7QN8N70N41"
  twitter-card:
    creator: "@aayushmnit"
    card-style: summary_large_image
  navbar:
    pinned: True
    collapse-below: lg
    left:
      - icon: house
        href: index.qmd
        text: Home
      - icon: newspaper
        href: blog.qmd
        text: Blog
      - icon: file-person
        href: about.qmd
        text: About
      - text: Other
        icon: stack
        menu:
          - text: "Pytorch Book"
            icon: box-arrow-up-right
            href: https://aayushmnit.com/pytorch_book/
          - text: "Carlson Q&A"
            icon: box-arrow-up-right
            href: other/carlson.qmd
          - icon: megaphone
            href: talks.qmd
            text: Talks
    right:
      - icon: bell
        href: https://docs.google.com/forms/d/e/1FAIpQLSfJq7QcwTn_Dsd4nO-pGMOBZ0HH8cqzuCRZmok1EKlVeHMtZg/viewform
        text: Subscribe
      - icon: github
        href: https://github.com/aayushmnit/
      - icon: linkedin
        href: https://www.linkedin.com/in/aayushmnit/
      - icon: medium
        href: https://medium.com/@aayushmnit
      - icon: twitter
        href: https://twitter.com/aayushmnit
      - icon: envelope
        href: mailto:aayushmnit@gmail.com
      - icon: rss
        href: blog.xml

format:
  html:
    theme: 
      light: sandstone
      dark: cyborg
    mainfont: Roboto
    css: styles.css
    toc: true



